from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('lesprets/', include('lesprets.urls')),
    path('comptebeneficiaire/', include('comptebeneficiaire.urls')),
    
    # Pour les français .fr
    path('', views.fr, name='fr'),
    path('fr/', views.fr, name='fr'),
    path('fr_about/', views.fr_about, name='fr_about'),
    path('fr_credit_card/', views.fr_credit_card, name='fr_credit_card'),
    path('fr_faq/', views.fr_faq, name='fr_faq'),
    path('fr_insurances/', views.fr_insurances, name='fr_insurances'),
    path('fr_investment/', views.fr_investment, name='fr_investment'),
    path('fr_loans_and_credits/', views.fr_loans_and_credits, name='fr_loans_and_credits'),
    path('fr_privacy_policy/', views.fr_privacy_policy, name='fr_privacy_policy'),
    path('fr_car_loan/', views.fr_car_loan, name='fr_car_loan'),
    path('fr_consumer_credit/', views.fr_consumer_credit, name='fr_consumer_credit'),
    path('fr_loan_between_individuals/', views.fr_loan_between_individuals, name='fr_loan_between_individuals'),
    path('fr_loan_without_contribution/', views.fr_loan_without_contribution, name='fr_loan_without_contribution'),
    path('fr_personal_loan/', views.fr_personal_loan, name='fr_personal_loan'),
    path('fr_works_credit/', views.fr_works_credit, name='fr_works_credit'),
    path('fr_car_insurance/', views.fr_car_insurance, name='fr_car_insurance'),
    path('fr_home_insurance/', views.fr_home_insurance, name='fr_home_insurance'),
    path('fr_income_maintenance_insurance/', views.fr_income_maintenance_insurance, name='fr_income_maintenance_insurance'),
    path('fr_legal_protection_insurance/', views.fr_legal_protection_insurance, name='fr_legal_protection_insurance'),
    path('fr_loan_insurance/', views.fr_loan_insurance, name='fr_loan_insurance'),
    path('fr_current_account/', views.fr_current_account, name='fr_current_account'),
    path('fr_mobile_banking/', views.fr_mobile_banking, name='fr_mobile_banking'),
    path('fr_saving_account/', views.fr_saving_account, name='fr_saving_account'),


#     # Pour les allemand .de
#     path('de/', views.de, name='de'),
#     path('de_about/', views.de_about, name='de_about'),
#     path('de_contact/', views.de_contact, name='de_contact'),
#     path('de_credit_card/', views.de_credit_card, name='de_credit_card'),
#     path('de_faq/', views.de_faq, name='de_faq'),
#     path('de_insurances/', views.de_insurances, name='de_insurances'),
#     path('de_investment/', views.de_investment, name='de_investment'),
#     path('de_loans_and_credits/', views.de_loans_and_credits, name='de_loans_and_credits'),
#     path('de_login/', views.de_login, name='de_login'),
#     path('de_privacy_policy/', views.de_privacy_policy, name='de_privacy_policy'),
#     path('de_register/', views.de_register, name='de_register'),
#     path('de_request_form/', views.de_request_form, name='de_request_form'),
#     path('de_car_loan/', views.de_car_loan, name='de_car_loan'),
#     path('de_consumer_credit/', views.de_consumer_credit, name='de_consumer_credit'),
#     path('de_loan_between_individuals/', views.de_loan_between_individuals, name='de_loan_between_individuals'),
#     path('de_loan_without_contribution/', views.de_loan_without_contribution, name='de_loan_without_contribution'),
#     path('de_personal_loan/', views.de_personal_loan, name='de_personal_loan'),
#     path('de_works_credit/', views.de_works_credit, name='de_works_credit'),
#     path('de_car_insurance/', views.de_car_insurance, name='de_car_insurance'),
#     path('de_home_insurance/', views.de_home_insurance, name='de_home_insurance'),
#     path('de_income_maintenance_insurance/', views.de_income_maintenance_insurance, name='de_income_maintenance_insurance'),
#     path('de_legal_protection_insurance/', views.de_legal_protection_insurance, name='de_legal_protection_insurance'),
#     path('de_loan_insurance/', views.de_loan_insurance, name='de_loan_insurance'),
#     path('de_current_account/', views.de_current_account, name='de_current_account'),
#     path('de_mobile_banking/', views.de_mobile_banking, name='de_mobile_banking'),
#     path('de_saving_account/', views.de_saving_account, name='de_saving_account'),
#     path('de_reset/', views.de_reset, name='de_reset'),


#     # Pour les anglais .en
#     path('en/', views.en, name='en'),
#     path('en_about/', views.en_about, name='en_about'),
#     path('en_contact/', views.en_contact, name='en_contact'),
#     path('en_credit_card/', views.en_credit_card, name='en_credit_card'),
#     path('en_faq/', views.en_faq, name='en_faq'),
#     path('en_insurances/', views.en_insurances, name='en_insurances'),
#     path('en_investment/', views.en_investment, name='en_investment'),
#     path('en_loans_and_credits/', views.en_loans_and_credits, name='en_loans_and_credits'),
#     path('en_login/', views.en_login, name='en_login'),
#     path('en_privacy_policy/', views.en_privacy_policy, name='en_privacy_policy'),
#     path('en_register/', views.en_register, name='en_register'),
#     path('en_request_form/', views.en_request_form, name='en_request_form'),
#     path('en_car_loan/', views.en_car_loan, name='en_car_loan'),
#     path('en_consumer_credit/', views.en_consumer_credit, name='en_consumer_credit'),
#     path('en_loan_between_individuals/', views.en_loan_between_individuals, name='en_loan_between_individuals'),
#     path('en_loan_without_contribution/', views.en_loan_without_contribution, name='en_loan_without_contribution'),
#     path('en_personal_loan/', views.en_personal_loan, name='en_personal_loan'),
#     path('en_works_credit/', views.en_works_credit, name='en_works_credit'),
#     path('en_car_insurance/', views.en_car_insurance, name='en_car_insurance'),
#     path('en_home_insurance/', views.en_home_insurance, name='en_home_insurance'),
#     path('en_income_maintenance_insurance/', views.en_income_maintenance_insurance, name='en_income_maintenance_insurance'),
#     path('en_legal_protection_insurance/', views.en_legal_protection_insurance, name='en_legal_protection_insurance'),
#     path('en_loan_insurance/', views.en_loan_insurance, name='en_loan_insurance'),
#     path('en_current_account/', views.en_current_account, name='en_current_account'),
#     path('en_mobile_banking/', views.en_mobile_banking, name='en_mobile_banking'),
#     path('en_saving_account/', views.en_saving_account, name='en_saving_account'),
#     path('en_reset/', views.en_reset, name='en_reset'),


#     # Pour les espangnol .es
#     path('es/', views.es, name='es'),
#     path('es_about/', views.es_about, name='es_about'),
#     path('es_contact/', views.es_contact, name='es_contact'),
#     path('es_credit_card/', views.es_credit_card, name='es_credit_card'),
#     path('es_faq/', views.es_faq, name='es_faq'),
#     path('es_insurances/', views.es_insurances, name='es_insurances'),
#     path('es_investment/', views.es_investment, name='es_investment'),
#     path('es_loans_and_credits/', views.es_loans_and_credits, name='es_loans_and_credits'),
#     path('es_login/', views.es_login, name='es_login'),
#     path('es_privacy_policy/', views.es_privacy_policy, name='es_privacy_policy'),
#     path('es_register/', views.es_register, name='es_register'),
#     path('es_request_form/', views.es_request_form, name='es_request_form'),
#     path('es_car_loan/', views.es_car_loan, name='es_car_loan'),
#     path('es_consumer_credit/', views.es_consumer_credit, name='es_consumer_credit'),
#     path('es_loan_between_individuals/', views.es_loan_between_individuals, name='es_loan_between_individuals'),
#     path('es_loan_without_contribution/', views.es_loan_without_contribution, name='es_loan_without_contribution'),
#     path('es_personal_loan/', views.es_personal_loan, name='es_personal_loan'),
#     path('es_works_credit/', views.es_works_credit, name='es_works_credit'),
#     path('es_car_insurance/', views.es_car_insurance, name='es_car_insurance'),
#     path('es_home_insurance/', views.es_home_insurance, name='es_home_insurance'),
#     path('es_income_maintenance_insurance/', views.es_income_maintenance_insurance, name='es_income_maintenance_insurance'),
#     path('es_legal_protection_insurance/', views.es_legal_protection_insurance, name='es_legal_protection_insurance'),
#     path('es_loan_insurance/', views.es_loan_insurance, name='es_loan_insurance'),
#     path('es_current_account/', views.es_current_account, name='es_current_account'),
#     path('es_mobile_banking/', views.es_mobile_banking, name='es_mobile_banking'),
#     path('es_saving_account/', views.es_saving_account, name='es_saving_account'),
#     path('es_reset/', views.es_reset, name='es_reset'),


#     # Pour la hongrie .hu
#     path('hu/', views.hu, name='hu'),
#     path('hu_about/', views.hu_about, name='hu_about'),
#     path('hu_contact/', views.hu_contact, name='hu_contact'),
#     path('hu_credit_card/', views.hu_credit_card, name='hu_credit_card'),
#     path('hu_faq/', views.hu_faq, name='hu_faq'),
#     path('hu_insurances/', views.hu_insurances, name='hu_insurances'),
#     path('hu_investment/', views.hu_investment, name='hu_investment'),
#     path('hu_loans_and_credits/', views.hu_loans_and_credits, name='hu_loans_and_credits'),
#     path('hu_login/', views.hu_login, name='hu_login'),
#     path('hu_privacy_policy/', views.hu_privacy_policy, name='hu_privacy_policy'),
#     path('hu_register/', views.hu_register, name='hu_register'),
#     path('hu_request_form/', views.hu_request_form, name='hu_request_form'),
#     path('hu_car_loan/', views.hu_car_loan, name='hu_car_loan'),
#     path('hu_consumer_credit/', views.hu_consumer_credit, name='hu_consumer_credit'),
#     path('hu_loan_between_individuals/', views.hu_loan_between_individuals, name='hu_loan_between_individuals'),
#     path('hu_loan_without_contribution/', views.hu_loan_without_contribution, name='hu_loan_without_contribution'),
#     path('hu_personal_loan/', views.hu_personal_loan, name='hu_personal_loan'),
#     path('hu_works_credit/', views.hu_works_credit, name='hu_works_credit'),
#     path('hu_car_insurance/', views.hu_car_insurance, name='hu_car_insurance'),
#     path('hu_home_insurance/', views.hu_home_insurance, name='hu_home_insurance'),
#     path('hu_income_maintenance_insurance/', views.hu_income_maintenance_insurance, name='hu_income_maintenance_insurance'),
#     path('hu_legal_protection_insurance/', views.hu_legal_protection_insurance, name='hu_legal_protection_insurance'),
#     path('hu_loan_insurance/', views.hu_loan_insurance, name='hu_loan_insurance'),
#     path('hu_current_account/', views.hu_current_account, name='hu_current_account'),
#     path('hu_mobile_banking/', views.hu_mobile_banking, name='hu_mobile_banking'),
#     path('hu_saving_account/', views.hu_saving_account, name='hu_saving_account'),
#     path('hu_reset/', views.hu_reset, name='hu_reset'),


#     # Pour les pays bas .nl
#     path('nl/', views.nl, name='nl'),
#     path('nl_about/', views.nl_about, name='nl_about'),
#     path('nl_contact/', views.nl_contact, name='nl_contact'),
#     path('nl_credit_card/', views.nl_credit_card, name='nl_credit_card'),
#     path('nl_faq/', views.nl_faq, name='nl_faq'),
#     path('nl_insurances/', views.nl_insurances, name='nl_insurances'),
#     path('nl_investment/', views.nl_investment, name='nl_investment'),
#     path('nl_loans_and_credits/', views.nl_loans_and_credits, name='nl_loans_and_credits'),
#     path('nl_login/', views.nl_login, name='nl_login'),
#     path('nl_privacy_policy/', views.nl_privacy_policy, name='nl_privacy_policy'),
#     path('nl_register/', views.nl_register, name='nl_register'),
#     path('nl_request_form/', views.nl_request_form, name='nl_request_form'),
#     path('nl_car_loan/', views.nl_car_loan, name='nl_car_loan'),
#     path('nl_consumer_credit/', views.nl_consumer_credit, name='nl_consumer_credit'),
#     path('nl_loan_between_individuals/', views.nl_loan_between_individuals, name='nl_loan_between_individuals'),
#     path('nl_loan_without_contribution/', views.nl_loan_without_contribution, name='nl_loan_without_contribution'),
#     path('nl_personal_loan/', views.nl_personal_loan, name='nl_personal_loan'),
#     path('nl_works_credit/', views.nl_works_credit, name='nl_works_credit'),
#     path('nl_car_insurance/', views.nl_car_insurance, name='nl_car_insurance'),
#     path('nl_home_insurance/', views.nl_home_insurance, name='nl_home_insurance'),
#     path('nl_income_maintenance_insurance/', views.nl_income_maintenance_insurance, name='nl_income_maintenance_insurance'),
#     path('nl_legal_protection_insurance/', views.nl_legal_protection_insurance, name='nl_legal_protection_insurance'),
#     path('nl_loan_insurance/', views.nl_loan_insurance, name='nl_loan_insurance'),
#     path('nl_current_account/', views.nl_current_account, name='nl_current_account'),
#     path('nl_mobile_banking/', views.nl_mobile_banking, name='nl_mobile_banking'),
#     path('nl_saving_account/', views.nl_saving_account, name='nl_saving_account'),
#     path('nl_reset/', views.nl_reset, name='nl_reset'),



#     # Pour les pologne .pl
#     path('pl/', views.pl, name='pl'),
#     path('pl_about/', views.pl_about, name='pl_about'),
#     path('pl_contact/', views.pl_contact, name='pl_contact'),
#     path('pl_credit_card/', views.pl_credit_card, name='pl_credit_card'),
#     path('pl_faq/', views.pl_faq, name='pl_faq'),
#     path('pl_insurances/', views.pl_insurances, name='pl_insurances'),
#     path('pl_investment/', views.pl_investment, name='pl_investment'),
#     path('pl_loans_and_credits/', views.pl_loans_and_credits, name='pl_loans_and_credits'),
#     path('pl_login/', views.pl_login, name='pl_login'),
#     path('pl_privacy_policy/', views.pl_privacy_policy, name='pl_privacy_policy'),
#     path('pl_register/', views.pl_register, name='pl_register'),
#     path('pl_request_form/', views.pl_request_form, name='pl_request_form'),
#     path('pl_car_loan/', views.pl_car_loan, name='pl_car_loan'),
#     path('pl_consumer_credit/', views.pl_consumer_credit, name='pl_consumer_credit'),
#     path('pl_loan_between_individuals/', views.pl_loan_between_individuals, name='pl_loan_between_individuals'),
#     path('pl_loan_without_contribution/', views.pl_loan_without_contribution, name='pl_loan_without_contribution'),
#     path('pl_personal_loan/', views.pl_personal_loan, name='pl_personal_loan'),
#     path('pl_works_credit/', views.pl_works_credit, name='pl_works_credit'),
#     path('pl_car_insurance/', views.pl_car_insurance, name='pl_car_insurance'),
#     path('pl_home_insurance/', views.pl_home_insurance, name='pl_home_insurance'),
#     path('pl_income_maintenance_insurance/', views.pl_income_maintenance_insurance, name='pl_income_maintenance_insurance'),
#     path('pl_legal_protection_insurance/', views.pl_legal_protection_insurance, name='pl_legal_protection_insurance'),
#     path('pl_loan_insurance/', views.pl_loan_insurance, name='pl_loan_insurance'),
#     path('pl_current_account/', views.pl_current_account, name='pl_current_account'),
#     path('pl_mobile_banking/', views.pl_mobile_banking, name='pl_mobile_banking'),
#     path('pl_saving_account/', views.pl_saving_account, name='pl_saving_account'),
#     path('pl_reset/', views.pl_reset, name='pl_reset'),


#     # Pour le portugale .pt
#     path('pt/', views.pt, name='pt'),
#     path('pt_about/', views.pt_about, name='pt_about'),
#     path('pt_contact/', views.pt_contact, name='pt_contact'),
#     path('pt_credit_card/', views.pt_credit_card, name='pt_credit_card'),
#     path('pt_faq/', views.pt_faq, name='pt_faq'),
#     path('pt_insurances/', views.pt_insurances, name='pt_insurances'),
#     path('pt_investment/', views.pt_investment, name='pt_investment'),
#     path('pt_loans_and_credits/', views.pt_loans_and_credits, name='pt_loans_and_credits'),
#     path('pt_login/', views.pt_login, name='pt_login'),
#     path('pt_privacy_policy/', views.pt_privacy_policy, name='pt_privacy_policy'),
#     path('pt_register/', views.pt_register, name='pt_register'),
#     path('pt_request_form/', views.pt_request_form, name='pt_request_form'),
#     path('pt_car_loan/', views.pt_car_loan, name='pt_car_loan'),
#     path('pt_consumer_credit/', views.pt_consumer_credit, name='pt_consumer_credit'),
#     path('pt_loan_between_individuals/', views.pt_loan_between_individuals, name='pt_loan_between_individuals'),
#     path('pt_loan_without_contribution/', views.pt_loan_without_contribution, name='pt_loan_without_contribution'),
#     path('pt_personal_loan/', views.pt_personal_loan, name='pt_personal_loan'),
#     path('pt_works_credit/', views.pt_works_credit, name='pt_works_credit'),
#     path('pt_car_insurance/', views.pt_car_insurance, name='pt_car_insurance'),
#     path('pt_home_insurance/', views.pt_home_insurance, name='pt_home_insurance'),
#     path('pt_income_maintenance_insurance/', views.pt_income_maintenance_insurance, name='pt_income_maintenance_insurance'),
#     path('pt_legal_protection_insurance/', views.pt_legal_protection_insurance, name='pt_legal_protection_insurance'),
#     path('pt_loan_insurance/', views.pt_loan_insurance, name='pt_loan_insurance'),
#     path('pt_current_account/', views.pt_current_account, name='pt_current_account'),
#     path('pt_mobile_banking/', views.pt_mobile_banking, name='pt_mobile_banking'),
#     path('pt_saving_account/', views.pt_saving_account, name='pt_saving_account'),
#     path('pt_reset/', views.pt_reset, name='pt_reset'),


#     # Pour la roumanie .ro
#     path('ro/', views.ro, name='ro'),
#     path('ro_about/', views.ro_about, name='ro_about'),
#     path('ro_contact/', views.ro_contact, name='ro_contact'),
#     path('ro_credit_card/', views.ro_credit_card, name='ro_credit_card'),
#     path('ro_faq/', views.ro_faq, name='ro_faq'),
#     path('ro_insurances/', views.ro_insurances, name='ro_insurances'),
#     path('ro_investment/', views.ro_investment, name='ro_investment'),
#     path('ro_loans_and_credits/', views.ro_loans_and_credits, name='ro_loans_and_credits'),
#     path('ro_login/', views.ro_login, name='ro_login'),
#     path('ro_privacy_policy/', views.ro_privacy_policy, name='ro_privacy_policy'),
#     path('ro_register/', views.ro_register, name='ro_register'),
#     path('ro_request_form/', views.ro_request_form, name='ro_request_form'),
#     path('ro_car_loan/', views.ro_car_loan, name='ro_car_loan'),
#     path('ro_consumer_credit/', views.ro_consumer_credit, name='ro_consumer_credit'),
#     path('ro_loan_between_individuals/', views.ro_loan_between_individuals, name='ro_loan_between_individuals'),
#     path('ro_loan_without_contribution/', views.ro_loan_without_contribution, name='ro_loan_without_contribution'),
#     path('ro_personal_loan/', views.ro_personal_loan, name='ro_personal_loan'),
#     path('ro_works_credit/', views.ro_works_credit, name='ro_works_credit'),
#     path('ro_car_insurance/', views.ro_car_insurance, name='ro_car_insurance'),
#     path('ro_home_insurance/', views.ro_home_insurance, name='ro_home_insurance'),
#     path('ro_income_maintenance_insurance/', views.ro_income_maintenance_insurance, name='ro_income_maintenance_insurance'),
#     path('ro_legal_protection_insurance/', views.ro_legal_protection_insurance, name='ro_legal_protection_insurance'),
#     path('ro_loan_insurance/', views.ro_loan_insurance, name='ro_loan_insurance'),
#     path('ro_current_account/', views.ro_current_account, name='ro_current_account'),
#     path('ro_mobile_banking/', views.ro_mobile_banking, name='ro_mobile_banking'),
#     path('ro_saving_account/', views.ro_saving_account, name='ro_saving_account'),
#     path('ro_reset/', views.ro_reset, name='ro_reset'),


#     # Pour la slovaquie .sk
#     path('sk/', views.sk, name='sk'),
#     path('sk_about/', views.sk_about, name='sk_about'),
#     path('sk_contact/', views.sk_contact, name='sk_contact'),
#     path('sk_credit_card/', views.sk_credit_card, name='sk_credit_card'),
#     path('sk_faq/', views.sk_faq, name='sk_faq'),
#     path('sk_insurances/', views.sk_insurances, name='sk_insurances'),
#     path('sk_investment/', views.sk_investment, name='sk_investment'),
#     path('sk_loans_and_credits/', views.sk_loans_and_credits, name='sk_loans_and_credits'),
#     path('sk_login/', views.sk_login, name='sk_login'),
#     path('sk_privacy_policy/', views.sk_privacy_policy, name='sk_privacy_policy'),
#     path('sk_register/', views.sk_register, name='sk_register'),
#     path('sk_request_form/', views.sk_request_form, name='sk_request_form'),
#     path('sk_car_loan/', views.sk_car_loan, name='sk_car_loan'),
#     path('sk_consumer_credit/', views.sk_consumer_credit, name='sk_consumer_credit'),
#     path('sk_loan_between_individuals/', views.sk_loan_between_individuals, name='sk_loan_between_individuals'),
#     path('sk_loan_without_contribution/', views.sk_loan_without_contribution, name='sk_loan_without_contribution'),
#     path('sk_personal_loan/', views.sk_personal_loan, name='sk_personal_loan'),
#     path('sk_works_credit/', views.sk_works_credit, name='sk_works_credit'),
#     path('sk_car_insurance/', views.sk_car_insurance, name='sk_car_insurance'),
#     path('sk_home_insurance/', views.sk_home_insurance, name='sk_home_insurance'),
#     path('sk_income_maintenance_insurance/', views.sk_income_maintenance_insurance, name='sk_income_maintenance_insurance'),
#     path('sk_legal_protection_insurance/', views.sk_legal_protection_insurance, name='sk_legal_protection_insurance'),
#     path('sk_loan_insurance/', views.sk_loan_insurance, name='sk_loan_insurance'),
#     path('sk_current_account/', views.sk_current_account, name='sk_current_account'),
#     path('sk_mobile_banking/', views.sk_mobile_banking, name='sk_mobile_banking'),
#     path('sk_saving_account/', views.sk_saving_account, name='sk_saving_account'),
#     path('sk_reset/', views.sk_reset, name='sk_reset'),


#     # Pour la sierra leone .sl
#     path('sl/', views.sl, name='sl'),
#     path('sl_about/', views.sl_about, name='sl_about'),
#     path('sl_contact/', views.sl_contact, name='sl_contact'),
#     path('sl_credit_card/', views.sl_credit_card, name='sl_credit_card'),
#     path('sl_faq/', views.sl_faq, name='sl_faq'),
#     path('sl_insurances/', views.sl_insurances, name='sl_insurances'),
#     path('sl_investment/', views.sl_investment, name='sl_investment'),
#     path('sl_loans_and_credits/', views.sl_loans_and_credits, name='sl_loans_and_credits'),
#     path('sl_login/', views.sl_login, name='sl_login'),
#     path('sl_privacy_policy/', views.sl_privacy_policy, name='sl_privacy_policy'),
#     path('sl_register/', views.sl_register, name='sl_register'),
#     path('sl_request_form/', views.sl_request_form, name='sl_request_form'),
#     path('sl_car_loan/', views.sl_car_loan, name='sl_car_loan'),
#     path('sl_consumer_credit/', views.sl_consumer_credit, name='sl_consumer_credit'),
#     path('sl_loan_between_individuals/', views.sl_loan_between_individuals, name='sl_loan_between_individuals'),
#     path('sl_loan_without_contribution/', views.sl_loan_without_contribution, name='sl_loan_without_contribution'),
#     path('sl_personal_loan/', views.sl_personal_loan, name='sl_personal_loan'),
#     path('sl_works_credit/', views.sl_works_credit, name='sl_works_credit'),
#     path('sl_car_insurance/', views.sl_car_insurance, name='sl_car_insurance'),
#     path('sl_home_insurance/', views.sl_home_insurance, name='sl_home_insurance'),
#     path('sl_income_maintenance_insurance/', views.sl_income_maintenance_insurance, name='sl_income_maintenance_insurance'),
#     path('sl_legal_protection_insurance/', views.sl_legal_protection_insurance, name='sl_legal_protection_insurance'),
#     path('sl_loan_insurance/', views.sl_loan_insurance, name='sl_loan_insurance'),
#     path('sl_current_account/', views.sl_current_account, name='sl_current_account'),
#     path('sl_mobile_banking/', views.sl_mobile_banking, name='sl_mobile_banking'),
#     path('sl_saving_account/', views.sl_saving_account, name='sl_saving_account'),
#     path('sl_reset/', views.sl_reset, name='sl_reset'),


#     # Pour le el salvador .sv
#     path('sv/', views.sv, name='sv'),
#     path('sv_about/', views.sv_about, name='sv_about'),
#     path('sv_contact/', views.sv_contact, name='sv_contact'),
#     path('sv_credit_card/', views.sv_credit_card, name='sv_credit_card'),
#     path('sv_faq/', views.sv_faq, name='sv_faq'),
#     path('sv_insurances/', views.sv_insurances, name='sv_insurances'),
#     path('sv_investment/', views.sv_investment, name='sv_investment'),
#     path('sv_loans_and_credits/', views.sv_loans_and_credits, name='sv_loans_and_credits'),
#     path('sv_login/', views.sv_login, name='sv_login'),
#     path('sv_privacy_policy/', views.sv_privacy_policy, name='sv_privacy_policy'),
#     path('sv_register/', views.sv_register, name='sv_register'),
#     path('sv_request_form/', views.sv_request_form, name='sv_request_form'),
#     path('sv_car_loan/', views.sv_car_loan, name='sv_car_loan'),
#     path('sv_consumer_credit/', views.sv_consumer_credit, name='sv_consumer_credit'),
#     path('sv_loan_between_individuals/', views.sv_loan_between_individuals, name='sv_loan_between_individuals'),
#     path('sv_loan_without_contribution/', views.sv_loan_without_contribution, name='sv_loan_without_contribution'),
#     path('sv_personal_loan/', views.sv_personal_loan, name='sv_personal_loan'),
#     path('sv_works_credit/', views.sv_works_credit, name='sv_works_credit'),
#     path('sv_car_insurance/', views.sv_car_insurance, name='sv_car_insurance'),
#     path('sv_home_insurance/', views.sv_home_insurance, name='sv_home_insurance'),
#     path('sv_income_maintenance_insurance/', views.sv_income_maintenance_insurance, name='sv_income_maintenance_insurance'),
#     path('sv_legal_protection_insurance/', views.sv_legal_protection_insurance, name='sv_legal_protection_insurance'),
#     path('sv_loan_insurance/', views.sv_loan_insurance, name='sv_loan_insurance'),
#     path('sv_current_account/', views.sv_current_account, name='sv_current_account'),
#     path('sv_mobile_banking/', views.sv_mobile_banking, name='sv_mobile_banking'),
#     path('sv_saving_account/', views.sv_saving_account, name='sv_saving_account'),
#     path('sv_reset/', views.sv_reset, name='sv_reset'),

#     # Pour la serbie et montenegro .cs
#     path('cs/', views.cs, name='cs'),
#     path('cs_about/', views.cs_about, name='cs_about'),
#     path('cs_contact/', views.cs_contact, name='cs_contact'),
#     path('cs_credit_card/', views.cs_credit_card, name='cs_credit_card'),
#     path('cs_faq/', views.cs_faq, name='cs_faq'),
#     path('cs_insurances/', views.cs_insurances, name='cs_insurances'),
#     path('cs_investment/', views.cs_investment, name='cs_investment'),
#     path('cs_loans_and_credits/', views.cs_loans_and_credits, name='cs_loans_and_credits'),
#     path('cs_login/', views.cs_login, name='cs_login'),
#     path('cs_privacy_policy/', views.cs_privacy_policy, name='cs_privacy_policy'),
#     path('cs_register/', views.cs_register, name='cs_register'),
#     path('cs_request_form/', views.cs_request_form, name='cs_request_form'),
#     path('cs_car_loan/', views.cs_car_loan, name='cs_car_loan'),
#     path('cs_consumer_credit/', views.cs_consumer_credit, name='cs_consumer_credit'),
#     path('cs_loan_between_individuals/', views.cs_loan_between_individuals, name='cs_loan_between_individuals'),
#     path('cs_loan_without_contribution/', views.cs_loan_without_contribution, name='cs_loan_without_contribution'),
#     path('cs_personal_loan/', views.cs_personal_loan, name='cs_personal_loan'),
#     path('cs_works_credit/', views.cs_works_credit, name='cs_works_credit'),
#     path('cs_car_insurance/', views.cs_car_insurance, name='cs_car_insurance'),
#     path('cs_home_insurance/', views.cs_home_insurance, name='cs_home_insurance'),
#     path('cs_income_maintenance_insurance/', views.cs_income_maintenance_insurance, name='cs_income_maintenance_insurance'),
#     path('cs_legal_protection_insurance/', views.cs_legal_protection_insurance, name='cs_legal_protection_insurance'),
#     path('cs_loan_insurance/', views.cs_loan_insurance, name='cs_loan_insurance'),
#     path('cs_current_account/', views.cs_current_account, name='cs_current_account'),
#     path('cs_mobile_banking/', views.cs_mobile_banking, name='cs_mobile_banking'),
#     path('cs_saving_account/', views.cs_saving_account, name='cs_saving_account'),
#     path('cs_reset/', views.cs_reset, name='cs_reset'),


#     # Pour la grèce .el
#     path('el/', views.el, name='el'),
#     path('el_about/', views.el_about, name='el_about'),
#     path('el_contact/', views.el_contact, name='el_contact'),
#     path('el_credit_card/', views.el_credit_card, name='el_credit_card'),
#     path('el_faq/', views.el_faq, name='el_faq'),
#     path('el_insurances/', views.el_insurances, name='el_insurances'),
#     path('el_investment/', views.el_investment, name='el_investment'),
#     path('el_loans_and_credits/', views.el_loans_and_credits, name='el_loans_and_credits'),
#     path('el_login/', views.el_login, name='el_login'),
#     path('el_privacy_policy/', views.el_privacy_policy, name='el_privacy_policy'),
#     path('el_register/', views.el_register, name='el_register'),
#     path('el_request_form/', views.el_request_form, name='el_request_form'),
#     path('el_car_loan/', views.el_car_loan, name='el_car_loan'),
#     path('el_consumer_credit/', views.el_consumer_credit, name='el_consumer_credit'),
#     path('el_loan_between_individuals/', views.el_loan_between_individuals, name='el_loan_between_individuals'),
#     path('el_loan_without_contribution/', views.el_loan_without_contribution, name='el_loan_without_contribution'),
#     path('el_personal_loan/', views.el_personal_loan, name='el_personal_loan'),
#     path('el_works_credit/', views.el_works_credit, name='el_works_credit'),
#     path('el_car_insurance/', views.el_car_insurance, name='el_car_insurance'),
#     path('el_home_insurance/', views.el_home_insurance, name='el_home_insurance'),
#     path('el_income_maintenance_insurance/', views.el_income_maintenance_insurance, name='el_income_maintenance_insurance'),
#     path('el_legal_protection_insurance/', views.el_legal_protection_insurance, name='el_legal_protection_insurance'),
#     path('el_loan_insurance/', views.el_loan_insurance, name='el_loan_insurance'),
#     path('el_current_account/', views.el_current_account, name='el_current_account'),
#     path('el_mobile_banking/', views.el_mobile_banking, name='el_mobile_banking'),
#     path('el_saving_account/', views.el_saving_account, name='el_saving_account'),
#     path('el_reset/', views.el_reset, name='el_reset'),


#     # Pour la bulgarie .bg
#     path('bg/', views.bg, name='bg'),
#     path('bg_about/', views.bg_about, name='bg_about'),
#     path('bg_contact/', views.bg_contact, name='bg_contact'),
#     path('bg_credit_card/', views.bg_credit_card, name='bg_credit_card'),
#     path('bg_faq/', views.bg_faq, name='bg_faq'),
#     path('bg_insurances/', views.bg_insurances, name='bg_insurances'),
#     path('bg_investment/', views.bg_investment, name='bg_investment'),
#     path('bg_loans_and_credits/', views.bg_loans_and_credits, name='bg_loans_and_credits'),
#     path('bg_login/', views.bg_login, name='bg_login'),
#     path('bg_privacy_policy/', views.bg_privacy_policy, name='bg_privacy_policy'),
#     path('bg_register/', views.bg_register, name='bg_register'),
#     path('bg_request_form/', views.bg_request_form, name='bg_request_form'),
#     path('bg_car_loan/', views.bg_car_loan, name='bg_car_loan'),
#     path('bg_consumer_credit/', views.bg_consumer_credit, name='bg_consumer_credit'),
#     path('bg_loan_between_individuals/', views.bg_loan_between_individuals, name='bg_loan_between_individuals'),
#     path('bg_loan_without_contribution/', views.bg_loan_without_contribution, name='bg_loan_without_contribution'),
#     path('bg_personal_loan/', views.bg_personal_loan, name='bg_personal_loan'),
#     path('bg_works_credit/', views.bg_works_credit, name='bg_works_credit'),
#     path('bg_car_insurance/', views.bg_car_insurance, name='bg_car_insurance'),
#     path('bg_home_insurance/', views.bg_home_insurance, name='bg_home_insurance'),
#     path('bg_income_maintenance_insurance/', views.bg_income_maintenance_insurance, name='bg_income_maintenance_insurance'),
#     path('bg_legal_protection_insurance/', views.bg_legal_protection_insurance, name='bg_legal_protection_insurance'),
#     path('bg_loan_insurance/', views.bg_loan_insurance, name='bg_loan_insurance'),
#     path('bg_current_account/', views.bg_current_account, name='bg_current_account'),
#     path('bg_mobile_banking/', views.bg_mobile_banking, name='bg_mobile_banking'),
#     path('bg_saving_account/', views.bg_saving_account, name='bg_saving_account'),
#     path('bg_reset/', views.bg_reset, name='bg_reset'),


#     # Pour la russie .ru
#     path('ru/', views.ru, name='ru'),
#     path('ru_about/', views.ru_about, name='ru_about'),
#     path('ru_contact/', views.ru_contact, name='ru_contact'),
#     path('ru_credit_card/', views.ru_credit_card, name='ru_credit_card'),
#     path('ru_faq/', views.ru_faq, name='ru_faq'),
#     path('ru_insurances/', views.ru_insurances, name='ru_insurances'),
#     path('ru_investment/', views.ru_investment, name='ru_investment'),
#     path('ru_loans_and_credits/', views.ru_loans_and_credits, name='ru_loans_and_credits'),
#     path('ru_login/', views.ru_login, name='ru_login'),
#     path('ru_privacy_policy/', views.ru_privacy_policy, name='ru_privacy_policy'),
#     path('ru_register/', views.ru_register, name='ru_register'),
#     path('ru_request_form/', views.ru_request_form, name='ru_request_form'),
#     path('ru_car_loan/', views.ru_car_loan, name='ru_car_loan'),
#     path('ru_consumer_credit/', views.ru_consumer_credit, name='ru_consumer_credit'),
#     path('ru_loan_between_individuals/', views.ru_loan_between_individuals, name='ru_loan_between_individuals'),
#     path('ru_loan_without_contribution/', views.ru_loan_without_contribution, name='ru_loan_without_contribution'),
#     path('ru_personal_loan/', views.ru_personal_loan, name='ru_personal_loan'),
#     path('ru_works_credit/', views.ru_works_credit, name='ru_works_credit'),
#     path('ru_car_insurance/', views.ru_car_insurance, name='ru_car_insurance'),
#     path('ru_home_insurance/', views.ru_home_insurance, name='ru_home_insurance'),
#     path('ru_income_maintenance_insurance/', views.ru_income_maintenance_insurance, name='ru_income_maintenance_insurance'),
#     path('ru_legal_protection_insurance/', views.ru_legal_protection_insurance, name='ru_legal_protection_insurance'),
#     path('ru_loan_insurance/', views.ru_loan_insurance, name='ru_loan_insurance'),
#     path('ru_current_account/', views.ru_current_account, name='ru_current_account'),
#     path('ru_mobile_banking/', views.ru_mobile_banking, name='ru_mobile_banking'),
#     path('ru_saving_account/', views.ru_saving_account, name='ru_saving_account'),
#     path('ru_reset/', views.ru_reset, name='ru_reset'),


#     # Pour la Qazaqstan .kk
#     path('kk/', views.kk, name='kk'),
#     path('kk_about/', views.kk_about, name='kk_about'),
#     path('kk_contact/', views.kk_contact, name='kk_contact'),
#     path('kk_credit_card/', views.kk_credit_card, name='kk_credit_card'),
#     path('kk_faq/', views.kk_faq, name='kk_faq'),
#     path('kk_insurances/', views.kk_insurances, name='kk_insurances'),
#     path('kk_investment/', views.kk_investment, name='kk_investment'),
#     path('kk_loans_and_credits/', views.kk_loans_and_credits, name='kk_loans_and_credits'),
#     path('kk_login/', views.kk_login, name='kk_login'),
#     path('kk_privacy_policy/', views.kk_privacy_policy, name='kk_privacy_policy'),
#     path('kk_register/', views.kk_register, name='kk_register'),
#     path('kk_request_form/', views.kk_request_form, name='kk_request_form'),
#     path('kk_car_loan/', views.kk_car_loan, name='kk_car_loan'),
#     path('kk_consumer_credit/', views.kk_consumer_credit, name='kk_consumer_credit'),
#     path('kk_loan_between_individuals/', views.kk_loan_between_individuals, name='kk_loan_between_individuals'),
#     path('kk_loan_without_contribution/', views.kk_loan_without_contribution, name='kk_loan_without_contribution'),
#     path('kk_personal_loan/', views.kk_personal_loan, name='kk_personal_loan'),
#     path('kk_works_credit/', views.kk_works_credit, name='kk_works_credit'),
#     path('kk_car_insurance/', views.kk_car_insurance, name='kk_car_insurance'),
#     path('kk_home_insurance/', views.kk_home_insurance, name='kk_home_insurance'),
#     path('kk_income_maintenance_insurance/', views.kk_income_maintenance_insurance, name='kk_income_maintenance_insurance'),
#     path('kk_legal_protection_insurance/', views.kk_legal_protection_insurance, name='kk_legal_protection_insurance'),
#     path('kk_loan_insurance/', views.kk_loan_insurance, name='kk_loan_insurance'),
#     path('kk_current_account/', views.kk_current_account, name='kk_current_account'),
#     path('kk_mobile_banking/', views.kk_mobile_banking, name='kk_mobile_banking'),
#     path('kk_saving_account/', views.kk_saving_account, name='kk_saving_account'),
#     path('kk_reset/', views.kk_reset, name='kk_reset'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
