# Generated by Django 3.1 on 2023-01-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBeneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomBanque', models.CharField(blank=True, max_length=1000)),
                ('nomBeneficiaire', models.CharField(blank=True, max_length=1000)),
                ('iban', models.CharField(blank=True, max_length=1000)),
                ('bic_swift', models.CharField(blank=True, max_length=1000)),
                ('pays', models.CharField(blank=True, max_length=1000)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
